# Generated by Django 3.2.8 on 2022-11-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=40, null=True)),
                ('system_name', models.CharField(blank=True, max_length=50, null=True)),
                ('drives', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
