# Generated by Django 3.2.8 on 2022-11-14 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(blank=True, max_length=50, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(verbose_name=datetime.date(2022, 11, 14))),
            ],
        ),
        migrations.AddField(
            model_name='systeminfos',
            name='folders',
            field=models.TextField(blank=True, null=True),
        ),
    ]
