# Generated by Django 3.2.8 on 2022-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20221114_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('system_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
