# Generated by Django 3.2.8 on 2022-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
