# Generated by Django 3.2.8 on 2022-11-15 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_action_action_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privatekey',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 11, 15)),
        ),
    ]
