# Generated by Django 3.2.8 on 2022-11-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20221115_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systeminfos',
            name='drives',
        ),
        migrations.AddField(
            model_name='systeminfos',
            name='roots',
            field=models.TextField(blank=True, null=True),
        ),
    ]
