# Generated by Django 3.2.8 on 2022-11-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20221115_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systeminfos',
            old_name='folders',
            new_name='items',
        ),
    ]
