# Generated by Django 3.2.8 on 2022-11-16 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_rename_folders_systeminfos_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='deactive_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 11, 16)),
        ),
    ]
